requires 'Mouse', '== 2.4.2';
requires 'Path::Tiny', '== 0.094';
requires 'Mojolicious';
requires 'DBI', '== 1.631';
requires 'DBD::mysql', '== 4.026';

on 'develop' => sub {
  requires 'B::Lint';
  requires "Pry";
}
