requires 'Mojolicious';
requires 'Mojolicious::Plugin::AssetPack';
requires 'CSS::Sass';
requires 'Mouse', '== 2.4.2';
requires 'Path::Tiny', '== 0.094';
requires 'DBI', '== 1.631';
requires 'DBD::mysql', '== 4.026';

on 'develop' => sub {
  requires "B::Lint";
  requires "Pry";
  requires "Term::ReadLine::Gnu";
  requires "Perl::Tidy";
}
